# Generated by Django 3.1.5 on 2021-01-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('location', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
